lines = []

lines.append("=" * 80)
lines.append("RAFEEQ - AI PATIENT COMPANION")
lines.append("COMPLETE PROJECT DOCUMENTATION")
lines.append("=" * 80)
lines.append("")
lines.append("Prepared for: Kenz Project")
lines.append("File format: Plain Text (.txt)")
lines.append("Covers: Libraries, Code, Requirements, Templates, Concept, Features, Bugs")
lines.append("")
lines.append("")
lines.append("=" * 80)
lines.append("TABLE OF CONTENTS")
lines.append("=" * 80)
lines.append("")
lines.append("1.  PROJECT CONCEPT AND OVERVIEW")
lines.append("2.  SYSTEM REQUIREMENTS")
lines.append("3.  ENVIRONMENT CONFIGURATION (.env)")
lines.append("4.  TECH STACK SUMMARY")
lines.append("5.  LIBRARIES AND DEPENDENCIES (DETAILED)")
lines.append("6.  PROJECT FOLDER STRUCTURE")
lines.append("7.  ARCHITECTURE OVERVIEW")
lines.append("8.  FILE-BY-FILE CODE BREAKDOWN")
lines.append("    8.1   index.html")
lines.append("    8.2   src/main.tsx")
lines.append("    8.3   src/App.tsx")
lines.append("    8.4   src/types/index.ts")
lines.append("    8.5   src/store/faceStore.ts")
lines.append("    8.6   src/store/voiceStore.ts")
lines.append("    8.7   useVoiceOrchestrator.ts")
lines.append("    8.8   useSpeechRecognition.ts")
lines.append("    8.9   useSpeechSynthesis.ts")
lines.append("    8.10  llmEngine.ts")
lines.append("    8.11  simpleResponseEngine.ts")
lines.append("    8.12  emergencyDetector.ts")
lines.append("    8.13  RafeeqFace.tsx")
lines.append("    8.14  Eyes.tsx / Eyebrows.tsx / Mouth.tsx")
lines.append("    8.15  springConfig.ts")
lines.append("    8.16  expressionAnimations.ts")
lines.append("    8.17  useFaceAnimations.ts")
lines.append("    8.18  useEyeTracking.ts")
lines.append("    8.19  Dashboard.tsx")
lines.append("    8.20  EmergencyOverlay.tsx")
lines.append("    8.21  ParticleBackground.tsx")
lines.append("    8.22  AudioVisualizer.tsx")
lines.append("    8.23  SplashOverlay.tsx")
lines.append("    8.24  StatusBar.tsx")
lines.append("    8.25  TranscriptDisplay.tsx")
lines.append("    8.26  PrivacyIndicator.tsx")
lines.append("    8.27  soundEffects.ts")
lines.append("    8.28  tokens.css / global.css / animations.css")
lines.append("9.  VOICE PIPELINE - FULL FLOW DIAGRAM")
lines.append("10. FACE STATE MACHINE")
lines.append("11. LLM ENGINE ROUTING LOGIC")
lines.append("12. CSS DESIGN SYSTEM")
lines.append("13. BUILD CONFIGURATION")
lines.append("14. FEATURES LIST")
lines.append("15. POTENTIAL BUGS AND KNOWN ISSUES")
lines.append("16. SECURITY NOTES")
lines.append("17. DEPLOYMENT NOTES")
lines.append("")
lines.append("")

# Section 1
lines.append("=" * 80)
lines.append("1. PROJECT CONCEPT AND OVERVIEW")
lines.append("=" * 80)
lines.append("")
lines.append("NAME: Rafeeq (Arabic: rafeeq = companion / friend)")
lines.append("")
lines.append("WHAT IS IT:")
lines.append("Rafeeq is a web-based AI patient companion for hospital and healthcare settings.")
lines.append("Target users:")
lines.append("  - Children (frightened or lonely in hospitals)")
lines.append("  - Elderly patients (difficulty with complex technology)")
lines.append("")
lines.append("The app presents as an animated talking AI face on a tablet/kiosk in a patient")
lines.append("room. Patients speak naturally; Rafeeq responds with voice. Voice-first design")
lines.append("requires no reading or typing ability.")
lines.append("")
lines.append("There is also a STAFF DASHBOARD for nurses/doctors showing patient wellbeing")
lines.append("summaries, pain levels, mood data, and critical alerts from AI conversations.")
lines.append("")
lines.append("DUAL VIEW ARCHITECTURE:")
lines.append("  1. COMPANION MODE - animated face, mic button, conversation transcript.")
lines.append("     Dark background, neon cyan color scheme. For patients.")
lines.append("  2. STAFF DASHBOARD - clinical data: patient table, alerts, pain charts.")
lines.append("     For hospital staff only.")
lines.append("")
lines.append("Both views are toggled with a single button in the top-right corner.")
lines.append("")
lines.append("PHASE STATUS:")
lines.append("Code comments say 'Phase 2: Voice Pipeline Active'. Phase 2 means the full")
lines.append("STT -> LLM -> TTS pipeline is wired and operational.")
lines.append("")
lines.append("")

# Section 2
lines.append("=" * 80)
lines.append("2. SYSTEM REQUIREMENTS")
lines.append("=" * 80)
lines.append("")
lines.append("RUNTIME (Browser):")
lines.append("  - Chrome 33+, Edge 79+, or Safari 14.1+ (Web Speech API required)")
lines.append("  - Microphone access permission required")
lines.append("  - JavaScript enabled")
lines.append("  - Audio output device (speakers/headphones) for TTS")
lines.append("")
lines.append("DEVELOPMENT:")
lines.append("  - Node.js 18+ (LTS recommended)")
lines.append("  - npm 9+")
lines.append("  - Internet connection (Google Fonts + LLM API calls)")
lines.append("")
lines.append("BROWSER COMPATIBILITY:")
lines.append("  Web Speech API is NOT supported in Firefox. The app handles this gracefully")
lines.append("  by disabling the mic button and showing an error message. Face animations")
lines.append("  and the dashboard work in all browsers.")
lines.append("")
lines.append("SUPPORTED LANGUAGES:")
lines.append("  - English (en-US) - primary")
lines.append("  - Arabic (ar/ar-SA) - auto-detected from speech character content")
lines.append("")
lines.append("")

# Section 3
lines.append("=" * 80)
lines.append("3. ENVIRONMENT CONFIGURATION (.env)")
lines.append("=" * 80)
lines.append("")
lines.append("Vite embeds VITE_* variables into the client JavaScript bundle at build time.")
lines.append("")
lines.append("CURRENT .env CONTENTS:")
lines.append("  VITE_LLM_API_KEY=02d7cd1f5d3c4b80bb21afbec2e5e7d6.tojdKuHMwJ3Jl3Yv")
lines.append("  VITE_LLM_BASE_URL=https://open.bigmodel.cn/api/paas/v4")
lines.append("  VITE_LLM_MODEL=glm-4-flash")
lines.append("  VITE_ELEVENLABS_API_KEY=  [EMPTY - ElevenLabs TTS disabled]")
lines.append("  VITE_ELEVENLABS_VOICE_ID=pNInz6obpgDQGcFmaJgB")
lines.append("  VITE_SHOW_DEV_TOOLS=false")
lines.append("")
lines.append("VARIABLE DESCRIPTIONS:")
lines.append("")
lines.append("  VITE_LLM_API_KEY")
lines.append("    API key for OpenAI-compatible LLM. Currently: Zhipu AI (GLM-4-Flash).")
lines.append("    If set, this provider is called first.")
lines.append("")
lines.append("  VITE_LLM_BASE_URL")
lines.append("    Base URL for the OpenAI-compatible API.")
lines.append("    Zhipu AI: https://open.bigmodel.cn/api/paas/v4")
lines.append("    Can swap to DeepSeek, local Ollama, or any compatible API.")
lines.append("")
lines.append("  VITE_LLM_MODEL")
lines.append("    Model identifier. 'glm-4-flash' is Zhipu's fast affordable model.")
lines.append("")
lines.append("  VITE_GEMINI_API_KEY")
lines.append("    Google Gemini API key (used if VITE_LLM_API_KEY is empty).")
lines.append("    Must start with 'AIzaSy' and be 30+ chars.")
lines.append("")
lines.append("  VITE_ELEVENLABS_API_KEY")
lines.append("    ElevenLabs TTS API key. Empty = falls back to browser Web Speech API.")
lines.append("    When set: cinematic voice quality with real audio-driven lip-sync.")
lines.append("")
lines.append("  VITE_ELEVENLABS_VOICE_ID")
lines.append("    Voice ID from ElevenLabs. Default: pNInz6obpgDQGcFmaJgB (Adam - calm male)")
lines.append("    .env.example also shows: 21m00Tcm4TlvDq8ikWAM (Rachel)")
lines.append("")
lines.append("  VITE_SHOW_DEV_TOOLS")
lines.append("    'true' shows StatusBar dev panel. Also auto-shown in Vite DEV mode.")
lines.append("")
lines.append("SECURITY WARNING:")
lines.append("  The .env file contains a REAL Zhipu AI API key. Vite embeds ALL VITE_*")
lines.append("  variables into the client JavaScript bundle. Anyone inspecting the built JS")
lines.append("  files can extract this key. Rotate it before publishing to any public repo.")
lines.append("")
lines.append("")

# Section 4
lines.append("=" * 80)
lines.append("4. TECH STACK SUMMARY")
lines.append("=" * 80)
lines.append("")
lines.append("  Framework:    React 19 (concurrent features)")
lines.append("  Language:     TypeScript 6")
lines.append("  Build Tool:   Vite 8")
lines.append("  Styling:      TailwindCSS 4 + CSS Modules + CSS Custom Properties")
lines.append("  Animations:   Framer Motion 12")
lines.append("  Icons:        Lucide React 1.25")
lines.append("  Charts:       Recharts 3")
lines.append("  State Mgmt:   Zustand 5")
lines.append("  Fonts:        IBM Plex Sans + IBM Plex Sans Arabic (Google Fonts)")
lines.append("  STT:          Web Speech API (browser-native)")
lines.append("  TTS:          ElevenLabs API (premium) / Web Speech API (fallback)")
lines.append("  LLM:          Zhipu GLM-4-Flash (primary) / Pollinations free (fallback)")
lines.append("  Audio FX:     Web Audio API (browser-native)")
lines.append("  Linting:      oxlint")
lines.append("")
lines.append("")

# Section 5
lines.append("=" * 80)
lines.append("5. LIBRARIES AND DEPENDENCIES (DETAILED)")
lines.append("=" * 80)
lines.append("")
lines.append("--- PRODUCTION DEPENDENCIES ---")
lines.append("")
lines.append("REACT (^19.2.7)")
lines.append("  The core UI framework. Component-based with virtual DOM.")
lines.append("  Usage: Every UI element is a React component.")
lines.append("  Key APIs: useState, useEffect, useRef, useCallback, createRoot, StrictMode")
lines.append("  Note: StrictMode renders twice in dev to catch side effects.")
lines.append("")
lines.append("REACT-DOM (^19.2.7)")
lines.append("  React's browser DOM renderer.")
lines.append("  Usage: createRoot(element).render(<App />) in main.tsx")
lines.append("")
lines.append("FRAMER MOTION (^12.42.2)")
lines.append("  Production-ready animation library. Spring physics, declarative animations.")
lines.append("  Usage:")
lines.append("    motion.svg  - Face SVG breathing scale animation")
lines.append("    motion.div  - EmergencyOverlay fade + spring entry")
lines.append("    motion.div  - TranscriptDisplay chat bubbles slide in")
lines.append("    motion.svg  - Emergency alert icon infinite pulse")
lines.append("    AnimatePresence - Mount/unmount transitions (interim text bar)")
lines.append("  Key APIs: motion.*, AnimatePresence, animate, initial, exit, transition")
lines.append("")
lines.append("LUCIDE-REACT (^1.25.0)")
lines.append("  SVG icon library as React components. Open-source fork of Feather Icons.")
lines.append("  Icons used:")
lines.append("    LayoutDashboard, UserRound (view toggle button in App.tsx)")
lines.append("    Activity, Users, BellRing, MessageSquare (dashboard summary cards)")
lines.append("    Bell, Settings (sidebar nav)")
lines.append("    X (close modal), ChevronRight (expand patient row)")
lines.append("    TrendingUp (pain chart), Frown, Smile, Meh, Moon (patient mood icons)")
lines.append("")
lines.append("RECHARTS (^3.9.2)")
lines.append("  Charting library built on D3, designed for React. SVG-based, animated.")
lines.append("  Usage: Patient detail modal - LineChart showing 24h pain trend.")
lines.append("  Components: LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip,")
lines.append("              ResponsiveContainer")
lines.append("")
lines.append("ZUSTAND (^5.0.14)")
lines.append("  Lightweight hook-based state management. Zero boilerplate, no Provider.")
lines.append("  Usage:")
lines.append("    faceStore.ts  - Face animation state (faceState, blinking, mouth,")
lines.append("                    pupilTarget, breathScale, isMicActive)")
lines.append("    voiceStore.ts - Voice state (isEmergency, voiceError, conversation,")
lines.append("                    lastResponse)")
lines.append("  Why not Context: Multiple unrelated components need these states.")
lines.append("  Zustand selectors prevent unnecessary re-renders unlike Context.")
lines.append("")
lines.append("--- DEV DEPENDENCIES ---")
lines.append("")
lines.append("VITE (^8.1.1)")
lines.append("  Next-generation build tool. Native ES modules in dev, Rollup for production.")
lines.append("  Scripts: npm run dev (port 5173), npm run build (->dist/), npm run preview")
lines.append("  Special: vite.config.ts proxies /api/pollinations -> text.pollinations.ai")
lines.append("           This avoids CORS issues when calling free Pollinations AI in dev.")
lines.append("")
lines.append("TYPESCRIPT (~6.0.2)")
lines.append("  Typed superset of JavaScript. All files are .ts or .tsx.")
lines.append("  Types defined in src/types/index.ts (FaceState, ConversationMessage, etc.)")
lines.append("")
lines.append("@VITEJS/PLUGIN-REACT (^6.0.3)")
lines.append("  Vite plugin enabling React JSX and Fast Refresh. Required for .tsx files.")
lines.append("")
lines.append("TAILWINDCSS (^4.3.3)")
lines.append("  Utility-first CSS framework. v4 uses CSS-first config (@import tailwindcss).")
lines.append("  Used inline in Dashboard.tsx. Less used in Companion mode (CSS Modules preferred).")
lines.append("")
lines.append("@TAILWINDCSS/POSTCSS (^4.3.3)")
lines.append("  PostCSS plugin required to process Tailwind CSS v4 during build.")
lines.append("")
lines.append("POSTCSS (^8.5.20)")
lines.append("  CSS transformation tool. Config: postcss.config.js uses @tailwindcss/postcss")
lines.append("  and autoprefixer.")
lines.append("")
lines.append("AUTOPREFIXER (^10.5.4)")
lines.append("  PostCSS plugin that adds vendor prefixes (-webkit-, -moz-) automatically.")
lines.append("")
lines.append("OXLINT (^1.71.0)")
lines.append("  Extremely fast JavaScript/TypeScript linter written in Rust.")
lines.append("  Run: npm run lint | Config: .oxlintrc.json")
lines.append("")
lines.append("@TYPES/* PACKAGES:")
lines.append("  @types/node (^24.13.2): Node.js types for build config files")
lines.append("  @types/react (^19.2.17): React component and hook types")
lines.append("  @types/react-dom (^19.2.3): React DOM types")
lines.append("")
lines.append("BROWSER-NATIVE APIs (no npm package):")
lines.append("  Web Speech API: window.SpeechRecognition / window.webkitSpeechRecognition (STT)")
lines.append("                  window.speechSynthesis (TTS)")
lines.append("  Web Audio API:  AudioContext, OscillatorNode, GainNode, AnalyserNode,")
lines.append("                  AudioBuffer (sound effects + ElevenLabs lip-sync)")
lines.append("  Canvas 2D API:  ParticleBackground.tsx animated particle field")
lines.append("  requestAnimationFrame: particle animation, breathing, mouth, eye tracking")
lines.append("")
lines.append("")

# Section 6
lines.append("=" * 80)
lines.append("6. PROJECT FOLDER STRUCTURE")
lines.append("=" * 80)
lines.append("")
lines.append("kenz project/")
lines.append("|-- .env                     Environment variables (active API keys)")
lines.append("|-- .env.example             Template for environment variables")
lines.append("|-- .gitignore               Git ignore rules")
lines.append("|-- .oxlintrc.json           Oxlint configuration")
lines.append("|-- README.md                Project readme")
lines.append("|-- index.html               HTML entry point")
lines.append("|-- package.json             npm package manifest")
lines.append("|-- package-lock.json        Locked dependency versions")
lines.append("|-- postcss.config.js        PostCSS configuration")
lines.append("|-- tailwind.config.js       Tailwind configuration")
lines.append("|-- tsconfig.json            TypeScript root config")
lines.append("|-- tsconfig.app.json        TypeScript app config")
lines.append("|-- tsconfig.node.json       TypeScript node config (build scripts)")
lines.append("|-- vite.config.ts           Vite build/dev configuration")
lines.append("|-- dist/                    Production build output (auto-generated)")
lines.append("|-- node_modules/            Installed dependencies (auto-generated)")
lines.append("|-- public/                  Static assets served as-is")
lines.append("|-- src/")
lines.append("    |-- App.module.css       CSS Module for App component")
lines.append("    |-- App.tsx              Root application component")
lines.append("    |-- index.css            Minimal CSS import file")
lines.append("    |-- main.tsx             Application entry point")
lines.append("    |-- assets/              Static asset imports")
lines.append("    |-- features/")
lines.append("    |   |-- dashboard/")
lines.append("    |   |   |-- Dashboard.tsx       Staff-facing clinical dashboard")
lines.append("    |   |-- emergency/")
lines.append("    |   |   |-- EmergencyOverlay.module.css")
lines.append("    |   |   |-- EmergencyOverlay.tsx     Full-screen emergency alert")
lines.append("    |   |-- face/")
lines.append("    |   |   |-- animations/")
lines.append("    |   |   |   |-- expressionAnimations.ts  Expression shape data per state")
lines.append("    |   |   |   |-- useEyeTracking.ts        Mouse/touch pupil tracking")
lines.append("    |   |   |   |-- useFaceAnimations.ts     Blink, breath, speaking mouth")
lines.append("    |   |   |-- components/")
lines.append("    |   |       |-- Eyebrows.tsx             Eyebrow SVG paths")
lines.append("    |   |       |-- Eyes.tsx                 Eye circles with pupils")
lines.append("    |   |       |-- Mouth.tsx                Mouth bezier curve")
lines.append("    |   |       |-- RafeeqFace.module.css    Face styles")
lines.append("    |   |       |-- RafeeqFace.tsx           Root face SVG component")
lines.append("    |   |       |-- springConfig.ts          Framer Motion spring presets")
lines.append("    |   |-- voice/")
lines.append("    |       |-- components/")
lines.append("    |       |   |-- MicButton.module.css")
lines.append("    |       |   |-- MicButton.tsx            Microphone toggle button")
lines.append("    |       |   |-- PrivacyIndicator.module.css")
lines.append("    |       |   |-- PrivacyIndicator.tsx     'Mic active' privacy badge")
lines.append("    |       |   |-- TranscriptDisplay.module.css")
lines.append("    |       |   |-- TranscriptDisplay.tsx    Chat bubbles + interim text")
lines.append("    |       |-- hooks/")
lines.append("    |       |   |-- useSpeechRecognition.ts  Web Speech API STT wrapper")
lines.append("    |       |   |-- useSpeechSynthesis.ts    ElevenLabs + Web Speech TTS")
lines.append("    |       |   |-- useVoiceOrchestrator.ts  Master voice pipeline hook")
lines.append("    |       |-- emergencyDetector.ts         Keyword-based emergency check")
lines.append("    |       |-- llmEngine.ts                 Multi-provider AI engine")
lines.append("    |       |-- simpleResponseEngine.ts      Offline fallback responses")
lines.append("    |-- shared/")
lines.append("    |   |-- components/")
lines.append("    |   |   |-- AudioVisualizer.tsx          Microphone audio bars")
lines.append("    |   |   |-- ParticleBackground.tsx       Canvas particle field")
lines.append("    |   |   |-- SplashOverlay.module.css")
lines.append("    |   |   |-- SplashOverlay.tsx            First-load splash screen")
lines.append("    |   |   |-- StatusBar.module.css")
lines.append("    |   |   |-- StatusBar.tsx                Dev face-state control panel")
lines.append("    |   |-- utils/")
lines.append("    |       |-- soundEffects.ts              Web Audio API tone generator")
lines.append("    |-- store/")
lines.append("    |   |-- faceStore.ts                     Zustand face animation state")
lines.append("    |   |-- voiceStore.ts                    Zustand voice/conversation state")
lines.append("    |-- styles/")
lines.append("    |   |-- animations.css                   CSS keyframe animations")
lines.append("    |   |-- global.css                       Global reset + base styles")
lines.append("    |   |-- tokens.css                       CSS design tokens")
lines.append("    |-- types/")
lines.append("        |-- index.ts                         Shared TypeScript types")
lines.append("        |-- speech.d.ts                      Web Speech API declarations")
lines.append("")
lines.append("")

# Section 7
lines.append("=" * 80)
lines.append("7. ARCHITECTURE OVERVIEW")
lines.append("=" * 80)
lines.append("")
lines.append("FEATURE-BASED ARCHITECTURE:")
lines.append("  1. voice     - STT + LLM + TTS pipeline")
lines.append("  2. face      - Animated SVG companion face")
lines.append("  3. dashboard - Staff clinical view")
lines.append("  4. emergency - Emergency detection and overlay")
lines.append("")
lines.append("SHARED LAYER:")
lines.append("  AudioVisualizer, ParticleBackground, SplashOverlay, StatusBar,")
lines.append("  soundEffects - shared across features.")
lines.append("")
lines.append("STATE MANAGEMENT:")
lines.append("  Two Zustand stores. No React Context, no prop drilling.")
lines.append("  faceStore:  all face animation properties")
lines.append("  voiceStore: voice pipeline state (conversation, errors, emergency)")
lines.append("")
lines.append("DATA FLOW IN COMPANION MODE:")
lines.append("  User speaks")
lines.append("  -> Web Speech API transcribes audio")
lines.append("  -> useSpeechRecognition emits final transcript")
lines.append("  -> useVoiceOrchestrator receives it")
lines.append("  -> emergencyDetector checks for phrases (synchronous, zero latency)")
lines.append("  -> IF emergency: EmergencyOverlay + TTS emergency message")
lines.append("  -> ELSE: setFaceState('thinking') + getGeminiResponse() [async]")
lines.append("  -> llmEngine: Zhipu -> Pollinations fallback -> offline fallback")
lines.append("  -> { text, positive } response")
lines.append("  -> speak(text), face animates, mouth syncs")
lines.append("  -> setFaceState('idle') after speech")
lines.append("")
lines.append("DASHBOARD DATA FLOW:")
lines.append("  ALL dashboard data is MOCK (static constants). No real backend.")
lines.append("  Pain charts use hardcoded data. Alerts are hardcoded.")
lines.append("")
lines.append("")

# Section 8
lines.append("=" * 80)
lines.append("8. FILE-BY-FILE CODE BREAKDOWN")
lines.append("=" * 80)
lines.append("")
lines.append("-" * 72)
lines.append("8.1 index.html (835 bytes, 23 lines)")
lines.append("-" * 72)
lines.append("HTML shell. Body contains only <div id='root'></div>.")
lines.append("Key elements:")
lines.append("  meta charset=UTF-8: supports Arabic")
lines.append("  meta name=description: 'Rafeeq - AI Patient Companion for children...'")
lines.append("  meta name=theme-color: #0d1117 (dark chrome on mobile)")
lines.append("  title: 'Rafeeq | AI Patient Companion'")
lines.append("  Google Fonts preconnect for faster loading")
lines.append("  IBM Plex Sans + IBM Plex Sans Arabic (weights 300/400/500/600)")
lines.append("  script type=module src=/src/main.tsx: Vite app entry")
lines.append("")
lines.append("-" * 72)
lines.append("8.2 src/main.tsx (379 bytes, 15 lines)")
lines.append("-" * 72)
lines.append("React entry point.")
lines.append("  1. Imports global.css (-> tokens.css + tailwindcss)")
lines.append("  2. Imports animations.css for CSS keyframes")
lines.append("  3. Gets #root element, throws Error if not found")
lines.append("  4. createRoot(element).render(<StrictMode><App /></StrictMode>)")
lines.append("NOTE: StrictMode renders TWICE in dev to catch side effects.")
lines.append("      May cause double API calls or audio glitches in dev mode.")
lines.append("")
lines.append("-" * 72)
lines.append("8.3 src/App.tsx (5,732 bytes, 157 lines)")
lines.append("-" * 72)
lines.append("Root component. Manages view toggle and all top-level rendering.")
lines.append("")
lines.append("STATE:")
lines.append("  view: 'companion' | 'dashboard' (local useState, default='dashboard')")
lines.append("")
lines.append("FROM STORES:")
lines.append("  faceState  - drives ambient glow data-state CSS attribute")
lines.append("  voiceError - displayed as error text")
lines.append("")
lines.append("VOICE PIPELINE: useVoiceOrchestrator() provides:")
lines.append("  interim, transcript, isListening, isSpeaking,")
lines.append("  isUnsupported, toggleListening")
lines.append("")
lines.append("TOP-RIGHT TOGGLE BUTTON:")
lines.append("  Fixed button, z-50, glass style with backdrop blur")
lines.append("  Icons: LayoutDashboard (->Staff Dashboard) / UserRound (->Companion)")
lines.append("")
lines.append("COMPANION VIEW LAYOUT (top to bottom):")
lines.append("  1. SplashOverlay - first-load fade-in")
lines.append("  2. ParticleBackground - canvas, always behind")
lines.append("  3. Ambient glow div - color shifts per faceState via data-state attr")
lines.append("  4. PrivacyIndicator - 'Mic Active' badge when isListening")
lines.append("  5. EmergencyOverlay - conditional full-screen red overlay")
lines.append("  6. <main>:")
lines.append("       header: 'r' Arabic logo + 'Rafeeq' title + 'AI Patient Companion'")
lines.append("       stage:  RafeeqFace + state label (key=faceState forces re-mount)")
lines.append("       transcriptRegion: TranscriptDisplay")
lines.append("       AudioVisualizer")
lines.append("       voiceSection: MicButton + error/unsupported messages")
lines.append("       footer: StatusBar (dev) + dev hint text")
lines.append("")
lines.append("STATE_LABELS dictionary:")
lines.append("  idle      -> 'Tap the mic to speak'")
lines.append("  listening -> 'I'm listening...'")
lines.append("  thinking  -> 'Let me think...'")
lines.append("  speaking  -> 'Speaking...'")
lines.append("  happy     -> 'That's wonderful!'")
lines.append("  concerned -> 'I'm here for you.'")
lines.append("  surprised -> 'Oh! Tell me more.'")
lines.append("  sleeping  -> 'Resting quietly...'")
lines.append("")
lines.append("-" * 72)
lines.append("8.4 src/types/index.ts (1,847 bytes, 56 lines)")
lines.append("-" * 72)
lines.append("All shared TypeScript types:")
lines.append("")
lines.append("  FaceState = 'idle'|'listening'|'thinking'|'speaking'|")
lines.append("              'happy'|'concerned'|'surprised'|'sleeping'")
lines.append("")
lines.append("  PupilTarget = { x: number; y: number } (range: -1 to 1)")
lines.append("")
lines.append("  MessageRole = 'patient' | 'assistant' | 'system'")
lines.append("")
lines.append("  ConversationMessage = {")
lines.append("    id: string")
lines.append("    role: MessageRole")
lines.append("    content: string")
lines.append("    timestamp: number  (Unix milliseconds)")
lines.append("    emotion?: FaceState  (optional)")
lines.append("  }")
lines.append("")
lines.append("  AppLanguage = 'en' | 'ar'")
lines.append("")
lines.append("  SpeechError = 'not-allowed'|'no-speech'|'audio-capture'|")
lines.append("                'network'|'aborted'|'unsupported'|'unknown'")
lines.append("  (maps directly to SpeechRecognitionErrorEvent.error codes)")
lines.append("")
lines.append("  EmergencyLevel = 'none' | 'detected'")
lines.append("")
lines.append("speech.d.ts: Ambient declarations for Web Speech API interfaces")
lines.append("  (SpeechRecognition, SpeechRecognitionEvent, SpeechRecognitionErrorEvent)")
lines.append("  not yet in standard TypeScript DOM lib.")
lines.append("")
lines.append("-" * 72)
lines.append("8.5 src/store/faceStore.ts (2,093 bytes, 67 lines)")
lines.append("-" * 72)
lines.append("Zustand store - SINGLE SOURCE OF TRUTH for face animation.")
lines.append("Everything that changes the face writes here.")
lines.append("")
lines.append("FIELDS + DEFAULTS:")
lines.append("  faceState:    FaceState = 'idle'")
lines.append("  isBlinking:   boolean = false")
lines.append("  mouthOpenness: number = 0  (0=closed, 1=open; clamped in setter)")
lines.append("  pupilTarget:  {x:0, y:0}  (normalized -1 to 1)")
lines.append("  breathScale:  number = 1  (oscillates 1.000 to 1.016)")
lines.append("  thinkingAngle: number = 0  (wraps at 360 in setter)")
lines.append("  isMicActive:  boolean = false")
lines.append("")
lines.append("All fields have setters. mouthOpenness clamped: Math.max(0,Math.min(1,v))")
lines.append("thinkingAngle wraps: value % 360")
lines.append("")
lines.append("WRITERS:")
lines.append("  useVoiceOrchestrator - setFaceState through pipeline")
lines.append("  useFaceAnimations    - setIsBlinking, setBreathScale, setMouthOpenness")
lines.append("  useEyeTracking       - setPupilTarget")
lines.append("  StatusBar (dev)      - manual faceState preview")
lines.append("")
lines.append("-" * 72)
lines.append("8.6 src/store/voiceStore.ts (1,678 bytes, 56 lines)")
lines.append("-" * 72)
lines.append("Zustand store for cross-cutting voice state.")
lines.append("Transient state (isListening, transcript) stays in hooks.")
lines.append("")
lines.append("FIELDS + DEFAULTS:")
lines.append("  isEmergency:  boolean = false")
lines.append("  voiceError:   string | null = null")
lines.append("  conversation: ConversationMessage[] = []")
lines.append("  lastResponse: string = ''")
lines.append("")
lines.append("ACTIONS:")
lines.append("  setIsEmergency(boolean)")
lines.append("  dismissEmergency()  ->  isEmergency = false")
lines.append("  setVoiceError(string | null)")
lines.append("  addMessage(omit<id,timestamp>)  ->  id='msg-N', timestamp=Date.now()")
lines.append("  clearConversation()")
lines.append("  setLastResponse(string)")
lines.append("")
lines.append("READERS: EmergencyOverlay, App.tsx, TranscriptDisplay, useVoiceOrchestrator")
lines.append("")
lines.append("-" * 72)
lines.append("8.7 useVoiceOrchestrator.ts (8,690 bytes, 249 lines)")
lines.append("-" * 72)
lines.append("THE MASTER HOOK. Wires STT -> Emergency Check -> LLM -> TTS.")
lines.append("")
lines.append("DEPENDENCIES:")
lines.append("  useSpeechRecognition, useSpeechSynthesis, faceStore, voiceStore,")
lines.append("  emergencyDetector, llmEngine, soundEffects")
lines.append("")
lines.append("CONSTANTS:")
lines.append("  THINKING_DELAY_MS = 0 (no artificial delay)")
lines.append("")
lines.append("CONTINUOUS MODE:")
lines.append("  isActiveRef (useRef) - tracks if session is active.")
lines.append("  User presses mic ONCE to start, ONCE to stop.")
lines.append("  Auto-restarts listening 600ms after each response ends.")
lines.append("")
lines.append("MOUTH SYNC via handleWordBoundary:")
lines.append("  Called on each word event. Every 4th word opens wider (emphasis).")
lines.append("  setTimeout decays openness naturally.")
lines.append("")
lines.append("5 useEffect HOOKS IN ORDER:")
lines.append("")
lines.append("  1. isListening effect:")
lines.append("     isListening=true -> faceState='listening', isMicActive=true,")
lines.append("     voiceError=null, playStartSound()")
lines.append("")
lines.append("  2. isSpeaking effect:")
lines.append("     isSpeaking=true  -> faceState='speaking'")
lines.append("     isSpeaking=false AND !isListening -> after 300ms:")
lines.append("       faceState='idle', mouthOpenness=0, isMicActive=false")
lines.append("")
lines.append("  3. Error effect:")
lines.append("     error -> map to SPEECH_ERROR_MESSAGES -> setVoiceError(msg)")
lines.append("     faceState='concerned', isMicActive=false, playErrorSound()")
lines.append("")
lines.append("  4. TRANSCRIPT EFFECT (core processing loop):")
lines.append("     transcript arrives -> setIsMicActive(false)")
lines.append("     addMessage({role:'patient', content:transcript})")
lines.append("     detectEmergency(transcript)  [SYNCHRONOUS - no network]")
lines.append("       IF emergency:")
lines.append("         setIsEmergency(true), faceState='concerned'")
lines.append("         playEmergencySound()")
lines.append("         addMessage(EMERGENCY_RESPONSE)")
lines.append("         speak(EMERGENCY_RESPONSE) -> RETURN")
lines.append("       ELSE:")
lines.append("         faceState='thinking', playThinkingSound()")
lines.append("         [async] getGeminiResponse(transcript, conversation)")
lines.append("         setLastResponse(text), addMessage({role:'assistant',...})")
lines.append("         If positive: faceState='happy', wait 400ms, speak(text)")
lines.append("         If not positive: speak(text) immediately")
lines.append("")
lines.append("  5. Auto-restart effect:")
lines.append("     !isListening AND !isSpeaking AND !error AND isActiveRef.current")
lines.append("     -> setTimeout 600ms -> startListening()")
lines.append("")
lines.append("TOGGLE FUNCTION:")
lines.append("  ON:  isActiveRef=true, startListening()")
lines.append("  OFF: isActiveRef=false, stopListening(), cancelSpeech(),")
lines.append("       faceState='idle', mouthOpenness=0, isMicActive=false")
lines.append("")
lines.append("RETURNS: {interim, transcript, isListening, isSpeaking, isUnsupported, toggleListening}")
lines.append("")
lines.append("-" * 72)
lines.append("8.8 useSpeechRecognition.ts (4,814 bytes, 153 lines)")
lines.append("-" * 72)
lines.append("Wraps browser Web Speech API SpeechRecognition.")
lines.append("")
lines.append("BROWSER DETECTION:")
lines.append("  Checks window.SpeechRecognition and window.webkitSpeechRecognition.")
lines.append("  null if unsupported (isSupported=false).")
lines.append("")
lines.append("CONFIGURATION:")
lines.append("  rec.continuous = false      (one utterance at a time - more reliable)")
lines.append("  rec.interimResults = true   (live partial text)")
lines.append("  rec.lang = 'en-US'")
lines.append("  rec.maxAlternatives = 1")
lines.append("")
lines.append("EVENT HANDLERS:")
lines.append("  onstart: isListening=true, clear error/transcript/interim")
lines.append("  onresult: separate final vs interim; setTranscript on final, setInterim on interim")
lines.append("  onerror: map via ERROR_MAP; 'aborted' is ignored (intentional stop)")
lines.append("  onend: isListening=false, interim=''")
lines.append("")
lines.append("Recognition instance created ONCE in useEffect, stored in ref.")
lines.append("")
lines.append("ERROR_MAP:")
lines.append("  'not-allowed'   -> 'not-allowed'")
lines.append("  'no-speech'     -> 'no-speech'")
lines.append("  'audio-capture' -> 'audio-capture'")
lines.append("  'network'       -> 'network'")
lines.append("  'aborted'       -> ignored (user stopped intentionally)")
lines.append("  else            -> 'unknown'")
lines.append("")
lines.append("RETURNS: {transcript, interim, isListening, isSupported, error,")
lines.append("          startListening, stopListening}")
lines.append("")
lines.append("-" * 72)
lines.append("8.9 useSpeechSynthesis.ts (7,143 bytes, 224 lines)")
lines.append("-" * 72)
lines.append("TTS with two tiers:")
lines.append("  Tier 1 (premium): ElevenLabs API + real audio-driven lip-sync")
lines.append("  Tier 2 (fallback): Browser Web Speech API + word boundary events")
lines.append("")
lines.append("VOICE SELECTION (Web Speech, priority order):")
lines.append("  1. Microsoft natural voices (Edge/Windows)")
lines.append("  2. Google voices (Chrome)")
lines.append("  3. Named: Daniel, Alex, Tom, Fred, Aria, Samantha, Victoria")
lines.append("  4. First available voice matching language")
lines.append("  Arabic: filters by lang.startsWith('ar')")
lines.append("")
lines.append("LANGUAGE DETECTION:")
lines.append("  Count Arabic chars (U+0600-U+06FF).")
lines.append("  If >30% of text is Arabic chars -> use 'ar' voice/language.")
lines.append("")
lines.append("ELEVENLABS INTEGRATION:")
lines.append("  POST https://api.elevenlabs.io/v1/text-to-speech/{voiceId}")
lines.append("  Model: eleven_multilingual_v2 (English + Arabic)")
lines.append("  Settings: stability=0.65, similarity_boost=0.75, style=0.25,")
lines.append("            use_speaker_boost=true")
lines.append("  Process:")
lines.append("    1. Get audio blob from API")
lines.append("    2. Decode with AudioContext.decodeAudioData()")
lines.append("    3. Create AnalyserNode (fftSize=256, smoothing=0.6)")
lines.append("    4. RAF loop reads frequency bins 2-50 (speech range ~200-4000Hz)")
lines.append("    5. avg > 15 -> fire onBoundary() -> drives mouth openness")
lines.append("  TRUE lip-sync from actual audio - not just word boundary events.")
lines.append("  AbortController enables cancellation mid-speech.")
lines.append("")
lines.append("WEB SPEECH FALLBACK settings:")
lines.append("  rate=0.82, pitch=1.04, volume=1.0")
lines.append("  Word boundary events fire onBoundary()")
lines.append("")
lines.append("cancelSpeech(): abort ElevenLabs + window.speechSynthesis.cancel()")
lines.append("")
lines.append("RETURNS: {speak, cancelSpeech, isSpeaking, isSupported}")
lines.append("")
lines.append("-" * 72)
lines.append("8.10 llmEngine.ts (7,800 bytes, 227 lines)")
lines.append("-" * 72)
lines.append("Universal LLM routing engine. Three providers with auto-fallback.")
lines.append("")
lines.append("PROVIDER FLAGS (evaluated at module load):")
lines.append("  USE_OPENAI = LLM_API_KEY.length>0 AND LLM_BASE_URL.length>0")
lines.append("  USE_GEMINI = !USE_OPENAI AND GEMINI_KEY.startsWith('AIzaSy') AND len>30")
lines.append("  Current: USE_OPENAI=true (Zhipu key set), USE_GEMINI=false")
lines.append("")
lines.append("SYSTEM PROMPT defines Rafeeq personality:")
lines.append("  - Fun, warm, intelligent AI companion")
lines.append("  - Dynamic conversational style")
lines.append("  - Supports Arabic and English")
lines.append("  - Shows emotions and curiosity")
lines.append("  REQUIRED OUTPUT FORMAT:")
lines.append("    { 'response': 'message text', 'positive': true/false }")
lines.append("  'positive' flag determines if face becomes happy or stays neutral.")
lines.append("")
lines.append("PROVIDER 1 - callOpenAI(transcript, history):")
lines.append("  POST {LLM_BASE_URL}/chat/completions")
lines.append("  Compatible with ANY OpenAI-format API (Zhipu, DeepSeek, Ollama...)")
lines.append("  Last 15 messages | temperature=0.9, top_p=0.95, max_tokens=2048")
lines.append("  Strips markdown fences from response | JSON parse with raw text fallback")
lines.append("")
lines.append("PROVIDER 2 - callGemini(transcript, history):")
lines.append("  POST generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash")
lines.append("  system_instruction field | response_mime_type='application/json'")
lines.append("  Last 15 messages")
lines.append("")
lines.append("PROVIDER 3 - callPollinations(transcript, history):")
lines.append("  POST /api/pollinations/ [Vite proxy -> text.pollinations.ai]")
lines.append("  FREE, no API key | model='openai' | last 10 messages")
lines.append("")
lines.append("ROUTING in getGeminiResponse():")
lines.append("  try {")
lines.append("    if USE_OPENAI: callOpenAI() -> on fail -> callPollinations()")
lines.append("    if USE_GEMINI: callGemini()  [no Pollinations fallback]")
lines.append("    else: callPollinations()")
lines.append("  } catch (all fail): getResponse() [offline simpleResponseEngine]")
lines.append("")
lines.append("RETURNS: { text: string, positive: boolean }")
lines.append("")
lines.append("-" * 72)
lines.append("8.11 simpleResponseEngine.ts (5,000 bytes, 178 lines)")
lines.append("-" * 72)
lines.append("Fully offline keyword-matching response engine. Zero network, zero latency.")
lines.append("Used when ALL AI providers fail. Always succeeds.")
lines.append("")
lines.append("TOPIC MATCHING (TOPICS array of {keywords, getResponse}):")
lines.append("  Greetings: 'hello','hi','hey','good morning','good evening',Arabic greetings")
lines.append("  Pain:      'pain','hurt','ache','back hurts', Arabic pain words")
lines.append("  Name:      'your name','who are you', Arabic equivalents")
lines.append("  How-r-u:   'how are you', Arabic variants")
lines.append("  Family:    'family','mom','dad', Arabic words")
lines.append("  Boredom:   'bored','boring', Arabic")
lines.append("  Tiredness: 'tired','sleep', Arabic")
lines.append("Each topic has 3-4 randomized response strings via pick() helper.")
lines.append("")
lines.append("FALLBACK CLASSIFICATION (no keyword match):")
lines.append("  isQuestion: question words regex OR ends with ?")
lines.append("  isPositive: positive word regex (good/great/nice/love/happy/fine/better)")
lines.append("  isQuestion -> deflect to doctor response")
lines.append("  isPositive -> generic positive response")
lines.append("  else       -> generic neutral response")
lines.append("")
lines.append("Arabic: keywords include Arabic BUT responses are English-only.")
lines.append("")
lines.append("-" * 72)
lines.append("8.12 emergencyDetector.ts (1,989 bytes, 56 lines)")
lines.append("-" * 72)
lines.append("CRITICAL SAFETY COMPONENT. Synchronous, no network, runs BEFORE any LLM.")
lines.append("")
lines.append("EMERGENCY_PHRASES (complete list):")
lines.append("  Direct help: 'help','emergency','call a nurse','call the doctor',")
lines.append("               'call 911','i need help','someone help','help me'")
lines.append("  Breathing:   \"can't breathe\",'cannot breathe','hard to breathe',")
lines.append("               'trouble breathing','chest pain','chest hurts',")
lines.append("               'heart attack','my heart'")
lines.append("  Severe pain: 'severe pain','extreme pain','unbearable pain','horrible pain',")
lines.append("               'i am dying',\"i'm dying\"")
lines.append("  Bleeding:    'bleeding',\"i'm bleeding\",'blood','injured','fell down','i fell'")
lines.append("  Consciousness: 'feeling faint','going to pass out','i feel dizzy',")
lines.append("                 'very dizzy','feeling very sick','very sick'")
lines.append("")
lines.append("SANITIZATION: toLowerCase + replace punctuation with spaces + collapse whitespace")
lines.append("DETECTION: string.includes() for each phrase - O(phrases x text_length)")
lines.append("")
lines.append("EMERGENCY_RESPONSE (exact TTS message):")
lines.append("  'I am alerting the hospital staff right now. Help is on the way.'")
lines.append("  'Please stay calm. You are not alone.'")
lines.append("")
lines.append("LIMITATION: Arabic emergency phrases NOT included.")
lines.append("")
lines.append("-" * 72)
lines.append("8.13 RafeeqFace.tsx (2,523 bytes, 78 lines)")
lines.append("-" * 72)
lines.append("Root face SVG component. Activates all animation loops.")
lines.append("SVG VIEWBOX: '0 0 240 200'")
lines.append("")
lines.append("ANIMATION LOOPS ACTIVATED:")
lines.append("  useBlink()           - random eye blinking")
lines.append("  useBreath()          - sine-wave scale oscillation")
lines.append("  useSpeakingMouth()   - mouth in speaking state")
lines.append("  useEyeTracking(ref)  - pupils track mouse/touch")
lines.append("")
lines.append("VISUAL ELEMENTS:")
lines.append("  When isListening: 3 concentric neon ring spans, staggered 0/500/1000ms")
lines.append("    Rings expand outward (listenRing keyframe)")
lines.append("  When isSpeaking: 5 waveform bar spans, staggered 0/90/180/270/360ms")
lines.append("  SVG: motion.svg, animate={{scale: breathScale}}, BREATH_SPRING transition")
lines.append("  Inside SVG: <Eyebrows />, <Eyes />, <Mouth />")
lines.append("")
lines.append("ACCESSIBILITY: role='img', aria-label='Rafeeq animated face'")
lines.append("")
lines.append("-" * 72)
lines.append("8.14 Eyes.tsx / Eyebrows.tsx / Mouth.tsx")
lines.append("-" * 72)
lines.append("")
lines.append("EYES.TSX:")
lines.append("  Two SVG circle groups. Centers: Left(75,82), Right(165,82)")
lines.append("  Each eye: main circle (Framer Motion: r, fillOpacity, scaleX, scaleY, offsetY)")
lines.append("            pupil (smaller circle, moves with pupilTarget)")
lines.append("            eyelid (rect slides down: 100%=closed, 0%=open)")
lines.append("  Data from getExpression(faceState).eye and .eyelid")
lines.append("  isBlinking=true -> eyelid slides fully down")
lines.append("")
lines.append("EYEBROWS.TSX:")
lines.append("  Two SVG quadratic bezier curve paths.")
lines.append("  Framer Motion animates: path morphing, rotate, offsetY, opacity")
lines.append("  Data from getExpression(faceState).eyebrow")
lines.append("")
lines.append("MOUTH.TSX:")
lines.append("  SVG path (bezier curve) for most states, ellipse for 'surprised'")
lines.append("  mouthOpenness modifies control point Y -> creates lip-sync effect")
lines.append("  Higher openness = control point moves more = wider mouth")
lines.append("")
lines.append("-" * 72)
lines.append("8.15 springConfig.ts (1,055 bytes)")
lines.append("-" * 72)
lines.append("Framer Motion spring presets:")
lines.append("  BREATH_SPRING:     {type:'spring', stiffness:30,  damping:12}  (slow/soft)")
lines.append("  EXPRESSION_SPRING: {type:'spring', stiffness:280, damping:22}  (snappy)")
lines.append("  PUPIL_SPRING:      {type:'spring', stiffness:400, damping:35}  (tight/fast)")
lines.append("  BLINK_TRANSITION:  {duration:0.06}                             (near-instant)")
lines.append("")
lines.append("-" * 72)
lines.append("8.16 expressionAnimations.ts (4,422 bytes, 130 lines)")
lines.append("-" * 72)
lines.append("Visual shape data for all 8 face states.")
lines.append("Each ExpressionTarget: eye, eyebrow, eyelid, mouth data.")
lines.append("")
lines.append("MOUTH PATH CONVENTION:")
lines.append("  'M startX startY Q controlX controlY endX endY'")
lines.append("  Left anchor x=85 y=150 | Right anchor x=155 y=150 | Control x=120 always")
lines.append("  control y > 150 = smile | = 150 = flat | < 150 = frown")
lines.append("")
lines.append("EXPRESSIONS:")
lines.append("  idle:      r=26 filled | smile (y=168) | neutral brows")
lines.append("  listening: r=31 filled | light smile (y=162) | brows up +2deg")
lines.append("  thinking:  scaleX=1.25 scaleY=0.42 (squint) | flat (y=150) | brows -3deg")
lines.append("             eyelid 30% closed | blink PAUSED")
lines.append("  speaking:  r=26 filled | mild smile (y=162) | normal brows")
lines.append("  happy:     r=33 filled (largest) | big smile (y=180) | brows +8deg -6px")
lines.append("  concerned: r=25 ring only (fillOpacity=0,strokeWidth=5.5) | frown (y=142)")
lines.append("             brows -6deg | eyelid 5% closed")
lines.append("  surprised: r=30 ring only strokeWidth=5.5 | oval ellipse mouth")
lines.append("             brows +12deg -10px (highest)")
lines.append("  sleeping:  scaleX=1.55 scaleY=0.07 (flat slits) | eyelid 100% closed")
lines.append("             brows opacity=0 (hidden) | breathing 1.9x slower")
lines.append("")
lines.append("-" * 72)
lines.append("8.17 useFaceAnimations.ts (4,066 bytes, 111 lines)")
lines.append("-" * 72)
lines.append("Three animation hooks:")
lines.append("")
lines.append("useBlink():")
lines.append("  Random eye blinks every 2500-6000ms")
lines.append("  Duration: 120ms | PAUSED in 'sleeping' and 'thinking'")
lines.append("")
lines.append("useBreath():")
lines.append("  Sine-wave scale: 1.000 to 1.016")
lines.append("  Period: 4400ms normal | 8360ms sleeping (1.9x slower)")
lines.append("  Uses requestAnimationFrame")
lines.append("")
lines.append("useSpeakingMouth():")
lines.append("  Active ONLY in 'speaking' state, resets to 0 otherwise")
lines.append("  Layered sines for irregular natural motion:")
lines.append("    raw = 0.38*|sin(t*2.9)| + 0.30*|sin(t*4.3+1.1)| + 0.18*|sin(t*7.7+2.3)|")
lines.append("  Clamped to [0,1] -> mouthOpenness in faceStore")
lines.append("  NOTE: Competes with handleWordBoundary during Web Speech word events")
lines.append("")
lines.append("-" * 72)
lines.append("8.18 useEyeTracking.ts (3,316 bytes, 88 lines)")
lines.append("-" * 72)
lines.append("Converts mouse/touch to normalized pupil targets.")
lines.append("")
lines.append("IDLE DRIFT (Lissajous figure-eight):")
lines.append("  x = sin(t*2*PI)*0.3  |  y = sin(t*4*PI)*0.15")
lines.append("  Period 6000ms | Starts immediately | Resumes after 3000ms no pointer")
lines.append("")
lines.append("POINTER TRACKING:")
lines.append("  Normalizes relative to face SVG center | Scale factor 0.6 | Clamp [-1,1]")
lines.append("  After 3000ms inactivity: idle drift resumes")
lines.append("")
lines.append("SLEEPING: pointer events ignored when faceState='sleeping'")
lines.append("")
lines.append("-" * 72)
lines.append("8.19 Dashboard.tsx (19,746 bytes, 315 lines)")
lines.append("-" * 72)
lines.append("Staff clinical dashboard. ALL DATA IS MOCK - no real backend.")
lines.append("")
lines.append("MOCK_PATIENTS (5):")
lines.append("  Eleanor Vance     Rm302 sad    pain=8 Post-op Knee Replacement")
lines.append("  Arthur Pendelton  Rm105 sleep  pain=2 Pneumonia Observation")
lines.append("  Sarah Connor      Rm410 happy  pain=1 Routine Maternity")
lines.append("  James Holden      Rm221 neutral pain=5 Lower Back Trauma")
lines.append("  Amos Burton       Rm315 happy  pain=3 Appendectomy")
lines.append("Each has an aiSummary text string of 2-3 sentences.")
lines.append("")
lines.append("MOCK_ALERTS (4):")
lines.append("  CRITICAL: Room 302 - 8/10 back pain (Just now)")
lines.append("  WARNING:  Room 105 - Nurse assistance (12 mins ago)")
lines.append("  INFO:     Room 410 - Daily AI summary done (25 mins ago)")
lines.append("  CRITICAL: Room 221 - Missed medication window (40 mins ago)")
lines.append("")
lines.append("PAIN_TREND_DATA: 6 points (08:00->6, 12:00->7, 16:00->9,")
lines.append("  20:00->8, 00:00->5, 04:00->8)")
lines.append("  NOTE: Same data shown for ALL patients (see Bug #13)")
lines.append("")
lines.append("LAYOUT:")
lines.append("  Sidebar (w-64 dark): Logo, Nav(Dashboard/Patients/Alerts/Settings),")
lines.append("                       Doctor profile (Dr. Sarah Jenkins, Lead Physician)")
lines.append("  Main:")
lines.append("    Header: 'Overview' + live date")
lines.append("    4 summary cards: Active Patients(24), Critical Alerts(2),")
lines.append("                     Avg Pain(4.2), AI Interactions(142)")
lines.append("    Patient table (2/3 width): name, room, mood, pain bar, last chat")
lines.append("    Live Alerts feed (1/3 width): color-coded severity cards")
lines.append("")
lines.append("PATIENT DETAIL MODAL:")
lines.append("  Opens on ChevronRight click | Closes on X or backdrop click")
lines.append("  Shows: name, mood icon, room, condition, pain level (large)")
lines.append("  AI Daily Summary box")
lines.append("  Pain Trend LineChart (Recharts)")
lines.append("  Action buttons (no logic implemented yet)")
lines.append("")
lines.append("SUB-COMPONENTS: NavItem, SummaryCard")
lines.append("")
lines.append("-" * 72)
lines.append("8.20 EmergencyOverlay.tsx (3,056 bytes, 90 lines)")
lines.append("-" * 72)
lines.append("Full-screen overlay when isEmergency=true. RED color scheme (not neon cyan).")
lines.append("Designed to be visible and readable from several feet away.")
lines.append("")
lines.append("ACCESSIBILITY:")
lines.append("  role='alertdialog', aria-modal='true', aria-live='assertive'")
lines.append("  Dismiss button id='emergency-dismiss-btn'")
lines.append("")
lines.append("ANIMATIONS: overlay fade 0->1 (200ms) | card spring from scale 0.9 y=20")
lines.append("  Alert icon: infinite pulse scale 1->1.12->1 (1s period)")
lines.append("")
lines.append("CONTENT:")
lines.append("  Warning triangle SVG (pulsing)")
lines.append("  'Help is on the way' heading")
lines.append("  'I'm alerting hospital staff... Stay calm...'")
lines.append("  'A nurse or doctor will arrive shortly.'")
lines.append("  'False Alarm - I'm OK' button -> dismissEmergency()")
lines.append("")
lines.append("-" * 72)
lines.append("8.21 ParticleBackground.tsx (3,744 bytes, 129 lines)")
lines.append("-" * 72)
lines.append("Canvas 2D animated background. 45 drifting particles + connection lines.")
lines.append("position:fixed, inset:0, pointer-events:none, aria-hidden.")
lines.append("")
lines.append("PARTICLE PROPERTIES (45 per screen):")
lines.append("  Velocity: vx/vy max +/-0.06 (very slow drift)")
lines.append("  Size: 0.8-2.8px | Alpha: 0.04-0.29 (oscillates)")
lines.append("  Hue: 185-210 (cyan/teal range)")
lines.append("  Wraps around screen edges with 10px margin")
lines.append("")
lines.append("PER FRAME:")
lines.append("  clearRect | update position + alpha | draw radial gradient glow (5x size)")
lines.append("  draw core dot | draw connection lines for pairs within 120px distance")
lines.append("  Line alpha: 0.025 * (1 - dist/120)")
lines.append("")
lines.append("-" * 72)
lines.append("8.22 AudioVisualizer.tsx (3,438 bytes)")
lines.append("-" * 72)
lines.append("Animated bar chart representing audio activity.")
lines.append("Shows active bars when isListening or isSpeaking, resting otherwise.")
lines.append("Different animation patterns for listening vs speaking states.")
lines.append("")
lines.append("-" * 72)
lines.append("8.23 SplashOverlay.tsx (1,763 bytes)")
lines.append("-" * 72)
lines.append("First-load splash screen with Rafeeq logo.")
lines.append("Fades out automatically after app initialization.")
lines.append("")
lines.append("-" * 72)
lines.append("8.24 StatusBar.tsx (5,861 bytes, 137 lines)")
lines.append("-" * 72)
lines.append("Developer control panel. ONLY shown when VITE_SHOW_DEV_TOOLS=true or DEV mode.")
lines.append("")
lines.append("KEYBOARD SHORTCUTS:")
lines.append("  1=idle  2=listening  3=thinking  4=speaking")
lines.append("  5=happy 6=concerned  7=surprised  8=sleeping")
lines.append("")
lines.append("Each button: mini inline SVG face icon + label + keyboard shortcut (kbd)")
lines.append("Icons are hand-drawn SVG: 40x32 viewBox, two circles (eyes) + path (mouth)")
lines.append("")
lines.append("-" * 72)
lines.append("8.25 TranscriptDisplay.tsx (3,514 bytes, 124 lines)")
lines.append("-" * 72)
lines.append("Conversation chat bubbles + live interim speech bar.")
lines.append("")
lines.append("TYPEWRITERTEXT component:")
lines.append("  Animates text char by char at 25ms intervals")
lines.append("  Shows blinking cursor while animating")
lines.append("  Active only on last AI response while speaking")
lines.append("")
lines.append("CONVERSATIONHISTORY component:")
lines.append("  All messages as motion.div bubbles (slide in from below)")
lines.append("  Patient: right-aligned style | Assistant: left-aligned style")
lines.append("  Last assistant msg gets TypewriterText treatment")
lines.append("  Auto-scrolls to bottom on new messages")
lines.append("")
lines.append("TRANSCRIPTDISPLAY (root):")
lines.append("  Shows ConversationHistory when conversation.length > 0")
lines.append("  Shows floating interim bar when isListening AND interim exists")
lines.append("  InterimBar: AnimatePresence, role='status', aria-live='polite'")
lines.append("")
lines.append("-" * 72)
lines.append("8.26 PrivacyIndicator.tsx (1,398 bytes)")
lines.append("-" * 72)
lines.append("Fixed privacy badge displayed when microphone is active.")
lines.append("Pulsing red/orange dot + 'Mic Active' text.")
lines.append("Hidden (aria-hidden) when isActive=false.")
lines.append("")
lines.append("-" * 72)
lines.append("8.27 soundEffects.ts (2,326 bytes, 77 lines)")
lines.append("-" * 72)
lines.append("Web Audio API oscillator sound effects. Singleton AudioContext.")
lines.append("Philosophy: gentle, warm, non-alarming tones for hospital environments.")
lines.append("All volumes 0.025-0.06 with exponential decay.")
lines.append("")
lines.append("SOUNDS:")
lines.append("  playStartSound():     C5(523Hz) -> E5(659Hz) sine | ascending, mic on")
lines.append("  playStopSound():      E5(659Hz) -> C5(523Hz) sine | descending, mic off")
lines.append("  playErrorSound():     E4(330Hz) -> C4(262Hz) triangle | soft error")
lines.append("  playEmergencySound(): A5(880Hz)+E5(660Hz) square x3 | urgent, distinct")
lines.append("  playThinkingSound():  A4(440Hz) sine | barely audible subtle tap")
lines.append("")
lines.append("-" * 72)
lines.append("8.28 tokens.css / global.css / animations.css")
lines.append("-" * 72)
lines.append("")
lines.append("TOKENS.CSS - CSS Custom Properties:")
lines.append("  Backgrounds: --color-bg-base:#000000 (pure black), surface:#080c12,")
lines.append("               elevated:#0d1520, glass:rgba(8,12,18,0.75)")
lines.append("  Neon:        --color-neon:#00e5f5 (THE single face color)")
lines.append("               --color-neon-dim: rgba(0,229,245,0.5)")
lines.append("               --color-neon-glow: rgba(0,229,245,0.35)")
lines.append("  Accents:     --color-accent-primary:#1a8cff (blue UI elements)")
lines.append("               --color-accent-warning:#ff9b21 (orange)")
lines.append("               --color-accent-danger:#ff4566 (red emergency)")
lines.append("  Text:        primary rgba(255,255,255,0.92), secondary 0.55, muted 0.30")
lines.append("  Font:        --font-sans: IBM Plex Sans, IBM Plex Sans Arabic, system-ui")
lines.append("  Sizes:       xs=0.75rem, sm=0.875rem, base=1rem, lg=1.125rem, xl=1.25rem")
lines.append("  Weights:     light=300, regular=400, medium=500, semibold=600")
lines.append("  Spacing:     8pt scale: space-1(0.25rem) to space-16(4rem)")
lines.append("  Radius:      sm=0.375rem, md=0.625rem, lg=1rem, xl=1.5rem, full=9999px")
lines.append("  Z-index:     base=0, above=10, overlay=100, emergency=9999")
lines.append("  Layout:      --face-size: min(420px, 85vw, 65vh)")
lines.append("")
lines.append("GLOBAL.CSS:")
lines.append("  @import tailwindcss | @import tokens.css")
lines.append("  Universal box-sizing:border-box, margin/padding reset")
lines.append("  Body: IBM Plex Sans, #000000 bg, antialiased")
lines.append("  Custom scrollbar: 4px, neon cyan thumb")
lines.append("  .sr-only: visually hidden, screen-reader accessible")
lines.append("  .glass-card: backdrop-blur + rgba background + subtle border")
lines.append("  :focus-visible: 2px neon outline (keyboard navigation)")
lines.append("")
lines.append("ANIMATIONS.CSS (keyframes):")
lines.append("  breatheGlow:  opacity/scale 0%-50%-100% (ambient glow breath)")
lines.append("  listenRing:   scale 1->1.6, opacity 0.8->0 (expanding rings)")
lines.append("  thinkOrbit:   rotate+translateX (orbiting thinking dot)")
lines.append("  dangerPulse:  box-shadow 0->20px->0 red rgba (emergency pulse)")
lines.append("  fadeIn:       opacity 0->1, translateY 8px->0 (entry)")
lines.append("  statusPulse:  opacity 1->0.4 (status badge blink)")
lines.append("  scanLine:     top 10%->90% (scan line for thinking state)")
lines.append("")
lines.append("")

# Section 9
lines.append("=" * 80)
lines.append("9. VOICE PIPELINE - FULL FLOW DIAGRAM")
lines.append("=" * 80)
lines.append("")
lines.append("User presses MicButton (or auto-restart in continuous mode)")
lines.append("  |")
lines.append("  v")
lines.append("useVoiceOrchestrator.toggleListening()")
lines.append("isActiveRef.current = true")
lines.append("  |")
lines.append("  v")
lines.append("useSpeechRecognition.startListening() -> SpeechRecognition.start()")
lines.append("  |")
lines.append("  v")
lines.append("[onstart event fires]")
lines.append("isListening=true -> faceState='listening' + playStartSound()")
lines.append("  |")
lines.append("  v")
lines.append("[User speaks - interim results stream in]")
lines.append("TranscriptDisplay shows live interim text in floating bar")
lines.append("  |")
lines.append("  v")
lines.append("[onresult - isFinal=true]")
lines.append("transcript = 'the user spoke this text'")
lines.append("interim = ''")
lines.append("  |")
lines.append("  v")
lines.append("[onend fires] -> isListening=false")
lines.append("  |")
lines.append("  v")
lines.append("useEffect sees new transcript -> setIsMicActive(false)")
lines.append("addMessage({role:'patient', content:transcript})")
lines.append("  |")
lines.append("  v")
lines.append("detectEmergency(transcript)  [SYNCHRONOUS - zero latency, no network]")
lines.append("  |")
lines.append("  +-------YES-----------+--------NO----------+")
lines.append("  |                                          |")
lines.append("  v                                          v")
lines.append("setIsEmergency(true)              setFaceState('thinking')")
lines.append("setFaceState('concerned')         playThinkingSound()")
lines.append("playEmergencySound()                         |")
lines.append("EmergencyOverlay appears                     v")
lines.append("speak(EMERGENCY_RESPONSE)         getGeminiResponse(transcript, history)")
lines.append("RETURN                            [ASYNC: 500ms to 3s typical]")
lines.append("                                             |")
lines.append("                          +---Zhipu OK------>|")
lines.append("                          |---Zhipu FAIL---> callPollinations()")
lines.append("                          |                  |---Poll FAIL-> getResponse()")
lines.append("                                             |")
lines.append("                                    { text, positive }")
lines.append("                                             |")
lines.append("                               setLastResponse(text)")
lines.append("                               addMessage({role:'assistant',...})")
lines.append("                                             |")
lines.append("                                  positive=true?")
lines.append("                                  /           \\")
lines.append("                               YES             NO")
lines.append("                                |               |")
lines.append("                         setFaceState      speak(text)")
lines.append("                           ('happy')       immediately")
lines.append("                         wait 400ms")
lines.append("                         speak(text)")
lines.append("                                |")
lines.append("                                v")
lines.append("useSpeechSynthesis.speak(text)")
lines.append("  ELEVENLABS_KEY set? -> YES: POST ElevenLabs, decode audio,")
lines.append("                              AnalyserNode drives mouth (real lip-sync)")
lines.append("                    -> NO:  SpeechSynthesisUtterance,")
lines.append("                            word boundary events drive mouth")
lines.append("  setIsSpeaking(true) -> setFaceState('speaking')")
lines.append("  [speech plays, mouth moves]")
lines.append("  |")
lines.append("  v")
lines.append("Speech ends -> setIsSpeaking(false)")
lines.append("300ms later: setFaceState('idle'), setMouthOpenness(0)")
lines.append("  |")
lines.append("  v")
lines.append("[if continuous mode and no error]")
lines.append("600ms wait -> startListening() [LOOP BACK TO TOP]")
lines.append("")
lines.append("")

# Section 10
lines.append("=" * 80)
lines.append("10. FACE STATE MACHINE")
lines.append("=" * 80)
lines.append("")
lines.append("IDLE")
lines.append("  Eyes: filled r=26 | Mouth: smile (control y=168)")
lines.append("  Brows: neutral | Rings/Waveform: none")
lines.append("  Blink: active (2.5-6s) | Eye track: active")
lines.append("  Label: 'Tap the mic to speak'")
lines.append("")
lines.append("LISTENING")
lines.append("  Eyes: filled r=31 (wider/attentive) | Mouth: slight smile (y=162)")
lines.append("  Brows: +2deg raised | 3 expanding neon rings (0/500/1000ms staggered)")
lines.append("  Blink: active | Eye track: active")
lines.append("  Label: 'I'm listening...'")
lines.append("")
lines.append("THINKING")
lines.append("  Eyes: squint scaleX=1.25 scaleY=0.42 | Eyelid: 30% closed")
lines.append("  Mouth: flat (y=150) | Brows: furrowed -3deg")
lines.append("  Blink: PAUSED | Eye track: active")
lines.append("  Label: 'Let me think...'")
lines.append("")
lines.append("SPEAKING")
lines.append("  Eyes: filled r=26 | Mouth: mouthOpenness controlled (lip-sync)")
lines.append("  5 waveform bars below face (0/90/180/270/360ms staggered)")
lines.append("  Blink: active | Eye track: active")
lines.append("  Label: 'Speaking...'")
lines.append("")
lines.append("HAPPY")
lines.append("  Eyes: filled r=33 (largest) | Mouth: big smile (y=180)")
lines.append("  Brows: +8deg raised, -6px offset (highest normal state)")
lines.append("  Blink: active | Eye track: active")
lines.append("  Label: 'That's wonderful!'")
lines.append("")
lines.append("CONCERNED")
lines.append("  Eyes: hollow rings (fillOpacity=0, strokeWidth=5.5) r=25")
lines.append("  Mouth: frown (y=142) | Brows: furrowed -6deg | Eyelid: 5% closed")
lines.append("  Blink: active | Eye track: active")
lines.append("  Label: 'I'm here for you.'")
lines.append("")
lines.append("SURPRISED")
lines.append("  Eyes: hollow rings strokeWidth=5.5 r=30 | Mouth: oval ellipse")
lines.append("  Brows: +12deg raised, -10px offset (highest)")
lines.append("  Blink: active | Eye track: active")
lines.append("  Label: 'Oh! Tell me more.'")
lines.append("")
lines.append("SLEEPING")
lines.append("  Eyes: flat slits scaleX=1.55 scaleY=0.07 | Eyelid: 100% closed")
lines.append("  Mouth: small smile (y=158) | Brows: hidden (opacity=0)")
lines.append("  Breath: 1.9x slower | Blink: PAUSED | Eye track: PAUSED")
lines.append("  Label: 'Resting quietly...'")
lines.append("")
lines.append("TRANSITIONS: EXPRESSION_SPRING (stiffness:280, damping:22)")
lines.append("")
lines.append("")

# Section 11
lines.append("=" * 80)
lines.append("11. LLM ENGINE ROUTING LOGIC")
lines.append("=" * 80)
lines.append("")
lines.append("MODULE-LOAD FLAGS:")
lines.append("  USE_OPENAI = LLM_API_KEY.length>0 AND LLM_BASE_URL.length>0")
lines.append("  USE_GEMINI = !USE_OPENAI AND GEMINI_KEY.startsWith('AIzaSy') AND len>30")
lines.append("  CURRENT:    USE_OPENAI=true, USE_GEMINI=false")
lines.append("")
lines.append("EFFECTIVE ROUTING (current config):")
lines.append("  1st: callOpenAI (Zhipu GLM-4-Flash)")
lines.append("    POST https://open.bigmodel.cn/api/paas/v4/chat/completions")
lines.append("    On failure -> 2nd attempt")
lines.append("  2nd: callPollinations (free, no key)")
lines.append("    POST /api/pollinations/ [Vite proxy -> text.pollinations.ai]")
lines.append("    On failure -> 3rd attempt")
lines.append("  3rd: getResponse() [offline simpleResponseEngine, always succeeds]")
lines.append("")
lines.append("POLLINATIONS PROXY NOTE:")
lines.append("  The Vite proxy ONLY exists during 'npm run dev'.")
lines.append("  Production builds do NOT have this proxy.")
lines.append("  Pollinations from production may fail due to CORS.")
lines.append("  If Zhipu fails in production: final backup is offline engine only.")
lines.append("")
lines.append("JSON OUTPUT CONTRACT:")
lines.append("  LLM is instructed to return: { 'response': '...', 'positive': true/false }")
lines.append("  'positive'=true -> faceState becomes 'happy'")
lines.append("  'positive'=false -> faceState stays neutral on response")
lines.append("")
lines.append("")

# Section 12
lines.append("=" * 80)
lines.append("12. CSS DESIGN SYSTEM")
lines.append("=" * 80)
lines.append("")
lines.append("COLOR PHILOSOPHY:")
lines.append("  Face uses ONE color: neon cyan (#00e5f5)")
lines.append("  Background: pure black (#000000) to maximize neon contrast")
lines.append("  Emergency overlay: RED (#ff4566) - deliberate visual break to signal urgency")
lines.append("")
lines.append("TYPOGRAPHY:")
lines.append("  IBM Plex Sans (Latin) paired with IBM Plex Sans Arabic for bilingual support")
lines.append("  Humanist sans-serif by IBM, designed for screen readability")
lines.append("  Loaded from Google Fonts, weights 300/400/500/600")
lines.append("")
lines.append("CSS MODULES (scoped class names auto-generated at build time):")
lines.append("  App.module.css, RafeeqFace.module.css, EmergencyOverlay.module.css,")
lines.append("  MicButton.module.css, PrivacyIndicator.module.css,")
lines.append("  TranscriptDisplay.module.css, SplashOverlay.module.css, StatusBar.module.css")
lines.append("")
lines.append("TAILWIND IN DASHBOARD:")
lines.append("  Dashboard.tsx uses Tailwind utilities inline for rapid development.")
lines.append("  Neon glows use drop-shadow utilities with custom rgba values.")
lines.append("  Glassmorphism uses backdrop-blur + bg-slate-900/40.")
lines.append("")
lines.append("")

# Section 13
lines.append("=" * 80)
lines.append("13. BUILD CONFIGURATION")
lines.append("=" * 80)
lines.append("")
lines.append("vite.config.ts:")
lines.append("  plugins: [react()]")
lines.append("  server.proxy: '/api/pollinations' -> 'https://text.pollinations.ai'")
lines.append("  (dev only; does not exist in production builds)")
lines.append("")
lines.append("tsconfig.app.json:")
lines.append("  target: ES2020 | lib: ES2020, DOM, DOM.Iterable")
lines.append("  strict: true | jsx: react-jsx | moduleResolution: bundler")
lines.append("")
lines.append("postcss.config.js: @tailwindcss/postcss + autoprefixer")
lines.append("")
lines.append("tailwind.config.js: content: src/**/*.{ts,tsx}")
lines.append("")
lines.append("SCRIPTS:")
lines.append("  npm run dev      vite                 (dev server, port 5173)")
lines.append("  npm run build    tsc -b && vite build  (compile + bundle -> dist/)")
lines.append("  npm run lint     oxlint                (run linter)")
lines.append("  npm run preview  vite preview          (preview production build)")
lines.append("")
lines.append("")

# Section 14
lines.append("=" * 80)
lines.append("14. FEATURES LIST")
lines.append("=" * 80)
lines.append("")
lines.append("COMPANION MODE - IMPLEMENTED:")
lines.append("  [x] Animated AI face: 8 distinct expressions via SVG + Framer Motion")
lines.append("  [x] Pupils follow mouse/touch cursor (spring physics)")
lines.append("  [x] Automatic random eye blinking (2.5-6s intervals)")
lines.append("  [x] Subtle sine-wave breathing animation on face SVG")
lines.append("  [x] Canvas particle background (45 particles, connection lines)")
lines.append("  [x] Voice-first: tap mic, speak naturally")
lines.append("  [x] Continuous listening mode (one press to start, one to stop)")
lines.append("  [x] Live interim transcript (real-time words as you speak)")
lines.append("  [x] Chat bubble conversation history with slide-in animations")
lines.append("  [x] Typewriter effect on AI responses synced to speech")
lines.append("  [x] Lip-sync: mouth driven by audio frequencies or word events")
lines.append("  [x] Audio visualizer bars (mic/TTS activity)")
lines.append("  [x] Sound effects: mic start/stop, error, emergency, thinking")
lines.append("  [x] Emergency keyword detection (synchronous, pre-LLM)")
lines.append("  [x] Emergency full-screen overlay with pulsing red alert icon")
lines.append("  [x] 'False Alarm' dismissal button on emergency overlay")
lines.append("  [x] Privacy 'Mic Active' badge when microphone is recording")
lines.append("  [x] Error messages for permission denied, no mic, network errors")
lines.append("  [x] Unsupported browser message (Firefox)")
lines.append("  [x] Bilingual: English primary, Arabic auto-detected")
lines.append("  [x] Splash screen on first load")
lines.append("  [x] 3-tier LLM fallback: Zhipu -> Pollinations -> offline engine")
lines.append("  [x] Offline fallback always works (no network required)")
lines.append("  [x] Developer face state preview panel (keys 1-8, hidden in prod)")
lines.append("  [x] Toggle between Companion and Staff Dashboard")
lines.append("")
lines.append("STAFF DASHBOARD - IMPLEMENTED:")
lines.append("  [x] 4 summary cards with neon glow icons")
lines.append("  [x] Patient status table (mood, pain bars, last chat time)")
lines.append("  [x] Patient detail modal on row expand")
lines.append("  [x] AI Daily Summary text per patient")
lines.append("  [x] 24h Pain Trend LineChart (Recharts)")
lines.append("  [x] Live Alerts feed (critical/warning/info severity)")
lines.append("  [x] Sidebar navigation with active state")
lines.append("  [x] Alert count badge on sidebar")
lines.append("  [x] Doctor profile in sidebar")
lines.append("  [x] Responsive grid layout")
lines.append("")
lines.append("NOT YET IMPLEMENTED:")
lines.append("  [ ] Real backend (all dashboard data is mock/static)")
lines.append("  [ ] Real emergency notification to hospital staff")
lines.append("  [ ] Patients / Alerts / Settings tab content")
lines.append("  [ ] Persistent conversation history (clears on refresh)")
lines.append("  [ ] Arabic speech recognition (STT is English-only)")
lines.append("  [ ] Arabic emergency phrases in detector")
lines.append("  [ ] ElevenLabs key (using browser voice currently)")
lines.append("  [ ] User authentication / login system")
lines.append("  [ ] Database integration")
lines.append("  [ ] Real-time multi-patient monitoring")
lines.append("  [ ] Per-patient pain trend data")
lines.append("")
lines.append("")

# Section 15
lines.append("=" * 80)
lines.append("15. POTENTIAL BUGS AND KNOWN ISSUES")
lines.append("=" * 80)
lines.append("")
lines.append("BUG 1: POLLINATIONS PROXY MISSING IN PRODUCTION")
lines.append("Severity: HIGH")
lines.append("The Vite proxy only exists during 'npm run dev'. Production builds have")
lines.append("no proxy. Direct calls to text.pollinations.ai may fail due to CORS.")
lines.append("Impact: If Zhipu fails in production, Pollinations fallback also fails.")
lines.append("Only offline simpleResponseEngine remains.")
lines.append("Fix: Deploy a backend proxy endpoint server-side.")
lines.append("")
lines.append("BUG 2: EXPOSED API KEY IN BROWSER BUNDLE")
lines.append("Severity: HIGH (Security)")
lines.append("VITE_* variables are compiled into client-side JS. The Zhipu key is")
lines.append("visible to anyone who inspects the built JS files or Network tab.")
lines.append("Impact: Key theft, unauthorized usage, billing charges.")
lines.append("Fix: Move AI calls to a backend proxy. Never put paid keys in VITE_* vars.")
lines.append("")
lines.append("BUG 3: ARABIC EMERGENCY DETECTION MISSING")
lines.append("Severity: HIGH (Patient Safety)")
lines.append("emergencyDetector.ts only has English phrases. Arabic speakers saying")
lines.append("emergency words will NOT trigger the emergency workflow.")
lines.append("Impact: Emergency not detected for Arabic-speaking patients.")
lines.append("Fix: Add Arabic emergency phrase translations to EMERGENCY_PHRASES array.")
lines.append("")
lines.append("BUG 4: STRICTMODE DOUBLE-RENDER SIDE EFFECTS")
lines.append("Severity: MEDIUM (Development Only)")
lines.append("React 19's StrictMode renders components twice in dev. Animation hooks")
lines.append("and sound effects may initialize twice.")
lines.append("Impact: Development only. Not present in production builds.")
lines.append("Fix: Ensure all useEffect cleanups cancel RAF loops, timers, and audio.")
lines.append("")
lines.append("BUG 5: SPEECH RECOGNITION LANGUAGE FIXED TO ENGLISH")
lines.append("Severity: MEDIUM")
lines.append("useSpeechRecognition.ts uses lang='en-US' always. Even though TTS")
lines.append("auto-detects Arabic, mic transcription is English-only.")
lines.append("Impact: Arabic patients cannot use voice input effectively.")
lines.append("Fix: Add language selection or detect intent; set rec.lang='ar-SA'.")
lines.append("")
lines.append("BUG 6: MOUTH ANIMATION CONFLICT")
lines.append("Severity: LOW-MEDIUM")
lines.append("useSpeakingMouth (RAF loop) and handleWordBoundary (word events) both")
lines.append("write to mouthOpenness during 'speaking' state. ElevenLabs AnalyserNode")
lines.append("is a third writer. All three compete.")
lines.append("Impact: Jittery or inconsistent mouth animation.")
lines.append("Fix: Only run one mouth driver at a time (feature flag per provider).")
lines.append("")
lines.append("BUG 7: NO POLLINATIONS FALLBACK FOR GEMINI BRANCH")
lines.append("Severity: LOW")
lines.append("If user configures Gemini and it fails, it throws directly to the outer")
lines.append("catch (offline fallback) without trying Pollinations first.")
lines.append("Fix: Add try/catch around callGemini() -> callPollinations() fallback.")
lines.append("")
lines.append("BUG 8: CONVERSATION HISTORY NOT PERSISTED")
lines.append("Severity: LOW")
lines.append("voiceStore.conversation is in-memory only. Page refresh clears history.")
lines.append("Impact: No session continuity.")
lines.append("Fix: Zustand persist middleware with localStorage.")
lines.append("")
lines.append("BUG 9: DASHBOARD TABS ARE NAVIGATION-ONLY")
lines.append("Severity: LOW (UX)")
lines.append("Patients, Alerts, Settings tabs update activeTab state but no content")
lines.append("renders for them. You always see the Overview content.")
lines.append("Fix: Add conditional content sections based on activeTab value.")
lines.append("")
lines.append("BUG 10: TYPEWRITERTEXT INTERVAL ON RAPID UNMOUNT")
lines.append("Severity: LOW")
lines.append("If parent unmounts rapidly (switching to Dashboard mid-speech), the")
lines.append("setInterval cleanup runs but may fire one final state update.")
lines.append("Impact: Possible React warning about unmounted component state update.")
lines.append("Fix: Use mounted ref pattern to guard state updates.")
lines.append("")
lines.append("BUG 11: AUDIOCONTEXT BLOCKED BY BROWSER AUTOPLAY POLICY")
lines.append("Severity: LOW")
lines.append("Some browsers block AudioContext until user interaction. Code checks for")
lines.append("'suspended' state but may still fail on strict browsers.")
lines.append("Impact: No sound effects on very first interaction.")
lines.append("Fix: Resume AudioContext inside first confirmed user gesture handler.")
lines.append("")
lines.append("BUG 12: ELEVENLABS CONCURRENT REQUEST RACE")
lines.append("Severity: LOW")
lines.append("Very rapid speech may start two ElevenLabs requests nearly simultaneously.")
lines.append("AbortController cancels previous but there is a small race window.")
lines.append("Impact: Brief audio overlap or delayed lip-sync.")
lines.append("Fix: Ensure abort fires before new fetch begins (not just 'around same time').")
lines.append("")
lines.append("BUG 13: PAIN TREND CHART SAME FOR ALL PATIENTS")
lines.append("Severity: LOW (UX/Accuracy)")
lines.append("PAIN_TREND_DATA is a single constant. All patient modals show identical chart.")
lines.append("Impact: Misleading data in clinical context.")
lines.append("Fix: Add individual trend data arrays to each patient in MOCK_PATIENTS.")
lines.append("")
lines.append("")

# Section 16
lines.append("=" * 80)
lines.append("16. SECURITY NOTES")
lines.append("=" * 80)
lines.append("")
lines.append("1. API KEYS IN CLIENT BUNDLE")
lines.append("   All VITE_* vars compiled into client JS. Zhipu key visible in devtools.")
lines.append("   Action: Use backend proxy for production. Never put paid keys in VITE_*.")
lines.append("")
lines.append("2. NO AUTHENTICATION")
lines.append("   No login or session management. Anyone with the URL can access everything.")
lines.append("   Action: Implement role-based auth before hospital deployment.")
lines.append("")
lines.append("3. PATIENT PRIVACY / HIPAA")
lines.append("   Voice audio text sent to third-party APIs (Zhipu, Pollinations, ElevenLabs)")
lines.append("   over HTTPS. No persistent patient voice storage in current implementation.")
lines.append("   HIPAA compliance requires Data Processing Agreements with these providers.")
lines.append("   Action: Legal review and DPAs before any real medical use.")
lines.append("")
lines.append("4. HTTPS REQUIRED IN PRODUCTION")
lines.append("   Web Speech API requires HTTPS. http:// silently disables microphone.")
lines.append("   Action: Ensure SSL/TLS certificate on deployment server.")
lines.append("")
lines.append("5. CORS EXPOSURE")
lines.append("   All AI calls made directly from browser. API credentials visible in")
lines.append("   browser Network tab. CORS relies on third-party service policies.")
lines.append("   Action: Move all AI calls to server-side proxy.")
lines.append("")
lines.append("")

# Section 17
lines.append("=" * 80)
lines.append("17. DEPLOYMENT NOTES")
lines.append("=" * 80)
lines.append("")
lines.append("BUILD:")
lines.append("  npm run build -> ./dist/ (static files)")
lines.append("")
lines.append("SERVE:")
lines.append("  Any static file server: nginx, Apache, Netlify, Vercel, GitHub Pages")
lines.append("  Configure server to route all requests to index.html (SPA routing)")
lines.append("  nginx example: try_files $uri $uri/ /index.html;")
lines.append("")
lines.append("ENVIRONMENT VARIABLES FOR PRODUCTION:")
lines.append("  Set via hosting platform dashboard (NOT in committed .env files)")
lines.append("  VITE_LLM_API_KEY, VITE_LLM_BASE_URL, VITE_LLM_MODEL")
lines.append("  VITE_GEMINI_API_KEY, VITE_ELEVENLABS_API_KEY, VITE_ELEVENLABS_VOICE_ID")
lines.append("  VITE_SHOW_DEV_TOOLS=false")
lines.append("")
lines.append("POLLINATIONS IN PRODUCTION:")
lines.append("  Vite proxy does NOT exist in production builds.")
lines.append("  Pollinations may work with direct browser calls (they support CORS)")
lines.append("  but is not guaranteed. Use backend proxy for reliability.")
lines.append("")
lines.append("BROWSER RECOMMENDATION:")
lines.append("  Best:            Google Chrome or Microsoft Edge (full Web Speech API)")
lines.append("  OK:              Safari macOS/iOS (Web Speech with some limits)")
lines.append("  NOT SUPPORTED:   Firefox (voice features completely unavailable)")
lines.append("")
lines.append("TABLET KIOSK DEPLOYMENT (intended use case):")
lines.append("  Face sized for tablets: min(420px, 85vw, 65vh)")
lines.append("  Designed for full-screen kiosk in patient rooms")
lines.append("  Options:")
lines.append("    Chrome kiosk mode: chrome.exe --kiosk http://yourapp.com")
lines.append("    iPad Guided Access: Settings -> Accessibility -> Guided Access")
lines.append("    Android MDM kiosk mode software")
lines.append("")
lines.append("PERFORMANCE:")
lines.append("  2-4 concurrent requestAnimationFrame loops during normal use")
lines.append("  (ParticleBackground, useBreath, useSpeakingMouth, useEyeTracking)")
lines.append("  All properly cleaned up in useEffect return functions.")
lines.append("  Tested targeting 60fps on low-end tablets.")
lines.append("")
lines.append("DEFAULT PORT: 5173 (Vite dev)")
lines.append("  Change: vite --port 3000 OR server: { port: 3000 } in vite.config.ts")
lines.append("")
lines.append("")
lines.append("=" * 80)
lines.append("END OF DOCUMENT")
lines.append("=" * 80)
lines.append("Total source files documented: ~35 files")
lines.append("Total project lines of code: ~3,500 (excluding node_modules)")
lines.append("Project directory: kenz project")
lines.append("App name: Rafeeq - AI Patient Companion")
lines.append("Primary users: Hospitalized children and elderly patients")
lines.append("Secondary users: Hospital staff (dashboard view)")
lines.append("Dev stage: Phase 2 - Voice Pipeline Active (functional prototype)")
lines.append("=" * 80)

with open('PROJECT_DOCUMENTATION.txt', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print("Done! Lines written:", len(lines))
